[project]
name = "cfn-template-dependency-visualization"
version = "0.0.6"
requires-python = ">=3.12"
dependencies =  [
    "cfn-flip >= 1.3.0",
    "colorama >= 0.4.6",
]

[project.scripts]
cfn-tdv = "cfntdv.main:main"
